### ISSUE TITLE
ConstantTrait - getConstants is protected

### ISSUE THREAD

**Issue by BramRoets** [sebastiaanluca/laravel-helpers#8]
ConstantTrait has a method getConstants() which is protected. Shouldn't this be public to be usable?  I'm not really sure how to use it's functionality with the current implementation.

**Comment by sebastiaanluca** [comment]
Yeah, copied this as-is from the original source where `getConstants` was never used but wrapped instead to implement per class. So a public method `getTypes()` would call `getConstants()` just to express the class method would return all constant types.

Seems like I made it public in release 0.5.2 though. Did you pull in the latest version?

Really need to make some time to get this package up-to-date and release a tested version 1 actually.

**Comment by BramRoets** [comment]
It seems we are indeed running an older version here. I'll update it when possible. Thanks !
